### ISSUE TITLE
Suggestion command to close the bot

### ISSUE THREAD

**Issue by 0xWise64** [DEMON1A/Discord-Recon#18]
# Summary:

- Suggestion command to shutdown the bot, in case the admin need to instantly shut down it.

# Code:

```python3
@client.command()
async def shutdown(ctx):
    for admin in ADMINS:
        if str(ctx.message.author) == admin:
            await ctx.send('**The bot has been closed!**')
            await ctx.bot.logout()
        else:
            await ctx.send('**You are not authorized Admin!**')
```

**Comment by DEMON1A** [comment]
I'm working on adding this to the code, but I have a few code edits, this code won't fit when the discord-server have more than one admin on the list, so if the admin that's trying to shutdown the bot is on `1` index of the list not `0`. the will return the auth error message and execute the command after it. you need to add a return to stop it when the process is done, then include the auth error message outside the loop.

Here's the code that will get added, let me know if there's any problems since I can't test it at the current time:

```python
@Client.command()
async def shutdown(ctx):
    for ADMIN in ADMINS:
        if str(ctx.message.author) == ADMIN:
            await ctx.send("**Stoping the bot based on admin command**")
            await ctx.bot.logout()
            return
        await ctx.send("**Only admins allowed to shutdown the bot**")
```

**Comment by 0xWise64** [comment]
Hello @DEMON1A, hmm, I do not see any difference explicitly or any negative impact on the bot when adding return except that it will send the two messages for the shutdown and unauthorized admin, but the bot will be closed at the end, in any case yes you are right I had to include return in the code in order not It sends the other message :)

Hope for you good day!
@0xWise64

**Comment by 0xWise64** [comment]
@DEMON1A , I just test your code and it's same results still sending the two messages.. adding `return` didn't do any thing here xD

Anyway here is the code that's will working well:

```python3
@client.command()
async def shutdown(ctx):
    for admin in ADMINS:
        if str(ctx.message.author) == admin:
            await ctx.send("**The bot has been closed!**")
            await ctx.bot.logout()
            return None
        else: pass
    await ctx.send('**You are not authorized Admin! :)**')
```

**Comment by DEMON1A** [comment]
Yeah the first example was my bad, P.S there's no need for the else it's on python by default and return doesn't need a value to return it.

Thanks for your help, this function will be added into discord-recon V0.0.5 next week, still working on some updates that will be added along with the new version like restart the bot, and new caching stuff to make the bot faster. I will let you know when i push these updates

**Comment by DEMON1A** [comment]
- The code has been added on this commit: 74827ed
Thanks for your help.
